name: example
description: Example usage of jaspr_supabase
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.16.1
  jaspr_supabase:
    path: ../
  supabase: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_builder: ^0.16.1
